apiVersion: v1
kind: Service
metadata:
  name: py-app-service
spec:
  type: NodePort
  selector:
    app: py-app
  ports:
    - port: 8070  # External port
      targetPort: 8070  # Container port
      nodePort: 30080  # Optional: Specify a node port (range: 30000-32767)
